services:
  db:
    image: mysql:8.0
    container_name: hethongbansach-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hethongbansach
      MYSQL_USER: book
      MYSQL_PASSWORD: book
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
