spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:hethongbansach}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME:book}
    password: ${DB_PASSWORD:book}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   # dùng seed.sql, không để Hibernate tự tạo bảng
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
